# Generated by Django 2.2.5 on 2020-02-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200224_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amenties',
            new_name='amenities',
        ),
    ]
